# Generated by Django 4.1.5 on 2023-01-19 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '상품 댓글', 'verbose_name_plural': '상품 댓글'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='shinhan_product_comment',
        ),
    ]
